# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class BlueprintsService:
    def __init__(self, client):
        self.client = client

    def ExecuteBlueprint(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        Execute a blueprint on the ZeroRobot
        It is method for POST /blueprints
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/blueprints"
        return self.client.post(uri, data, headers, query_params, content_type)
